[font]
size = 10.0

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "Regular"

[colors.primary]
background= '#1d1f21'
foreground= '#c5c8c6'

[colors.normal]
black=   '#1d1f21'
red=     '#cc6666'
green=   '#b5bd68'
yellow=  '#f0c674'
blue=    '#81a2be'
magenta= '#b294bb'
cyan=    '#8abeb7'
white=   '#c5c8c6'

[colors.bright]
black=   '#969896'
red=     '#cc6666'
green=   '#b5bd68'
yellow=  '#f0c674'
blue=    '#81a2be'
magenta= '#b294bb'
cyan=    '#8abeb7'
white=   '#ffffff'

[cursor]
thickness = 0.15
